name: CI

on:
  push:
    branches:
    - master

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Build
        run: |
          gem install bundler
          bundle install
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: elindsey/jekyll-publish-action@master
