name: CI

on:
  push:
    branches:
    - master

jobs:
  build_and_deploy:
    #runs-on: windows-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/build-jekyll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #- uses: actions/setup-ruby@v1
      #  with:
      #    ruby-version: 2.6
      #- name: Build
      #  run: |
      #    gem install bundler
      #    bundle install
      #- env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #- name: Git fuckyery
      #  run: sh ./.github/workflows/test.sh
